server:
  port: 8080

spring:
  application:
    name: oceanbase-example
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    vectorstore:
      oceanbase:
        enabled: true
        url: ${OCEANBASE_URL:jdbc:oceanbase://localhost:2881/springai}
        username: ${OCEANBASE_USERNAME:root@test}
        password: ${OCEANBASE_PASSWORD:test}
        tableName: test_ai
        dimension: 1024  # Optional default 1024
        hybrid-search-type: fulltext #Optional, full-text indexes will be automatically created when enabled and support full-text + vector hybrid search